/* eslint-disable no-restricted-syntax,import/no-extraneous-dependencies */
const fs = require('fs');
const path = require('path');
const {
  warn, info, done,
} = require('@vue/cli-shared-utils');
const hereConfig = require('./.hererc');

// compiled files to `../public` or './dist`
let outputDirectory = null;
for (const dir of [...hereConfig.outputDir.test, hereConfig.outputDir.default]) {
  const absolutePath = path.resolve(dir);
  if (fs.existsSync(absolutePath) && fs.lstatSync(absolutePath).isDirectory()) {
    outputDirectory = absolutePath;
    break;
  }
}

// make default directory
if (outputDirectory === null) {
  warn('Cannot found any exists directory to store compiled files');
  outputDirectory = hereConfig.outputDir.default;
  fs.mkdirSync(outputDirectory);
  info(`The default directory was autogenerated -> '${outputDirectory}'`);
}

done(`Build directory -> '${outputDirectory}'`);
// export vue configure
module.exports = {
  // the directory where the production build files will be generated
  outputDir: outputDirectory,
  // don't need source maps for production
  productionSourceMap: false,
};
